# Generated by Django 6.0.3 on 2026-05-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='orderitem',
                    name='price',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                migrations.AlterField(
                    model_name='orderitem',
                    name='quantity',
                    field=models.IntegerField(default=1),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='orderitem',
                    name='price',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                migrations.AlterField(
                    model_name='orderitem',
                    name='quantity',
                    field=models.IntegerField(default=1),
                ),
            ]
        )
    ]
