# Generated by Django 6.0.3 on 2026-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='orderitem',
                    name='product_name',
                    field=models.CharField(default='', max_length=255),
                ),
            ]
        )
    ]
