# Generated by Django 6.0.3 on 2026-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_product_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='orderitem',
                    name='price',
                    field=models.DecimalField(decimal_places=2, max_digits=10),
                ),
                migrations.AlterField(
                    model_name='orderitem',
                    name='product_name',
                    field=models.CharField(max_length=255),
                ),
            ]
        )
    ]
