# Generated by Django 6.0.3 on 2026-03-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
