# Generated by Django 6.0.3 on 2026-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
