# Generated by Django 6.0.3 on 2026-08-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_stock_restored',
            field=models.BooleanField(default=False),
        ),
    ]
