# Generated by Django 6.0.3 on 2026-06-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_banner_button_text_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cashback_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='banner',
            name='offer_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.product'),
        ),
    ]
