# Generated by Django 6.0.3 on 2026-06-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner_cashback_text_banner_offer_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='badge_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('premium', 'Premium Banner'), ('sale', 'Sale/Promo Banner'), ('countdown', 'Countdown Urgent Offer'), ('new_arrival', 'New Arrival Spotlight'), ('sports', 'Sports Athletic Theme'), ('minimal', 'Luxury Minimalist')], default='premium', max_length=30),
        ),
        migrations.AddField(
            model_name='banner',
            name='countdown_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_banners', to='products.product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='secondary_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
