# Generated by Django 6.0.3 on 2026-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_background_color_banner_badge_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('premium', 'Premium Banner'), ('sale', 'Sale/Promo Banner'), ('countdown', 'Countdown Urgent Offer'), ('new_arrival', 'New Arrival Spotlight'), ('sports', 'Sports Athletic Theme'), ('minimal', 'Luxury Minimalist'), ('full_width', 'Full-width Hero Banner')], default='premium', max_length=30),
        ),
    ]
