# Generated by Django 6.0.3 on 2026-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('hockey', 'Hockey'), ('sports cycle', 'Sports Cycle')], max_length=50),
        ),
    ]
