# Generated by Django 6.0.3 on 2026-06-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_best_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='featured_in_banners', to='products.product'),
        ),
        migrations.AddField(
            model_name='banner',
            name='linked_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_banners', to='products.category'),
        ),
    ]
