# Generated by Django 6.0.3 on 2026-07-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_banner_description_banner_featured_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['priority', 'display_order', '-id']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cashback_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='countdown_end',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='featured_products',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='linked_category',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='linked_product',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='offer_percent',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='secondary_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/desktop/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/mobile/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('flash_sale', 'Flash Sale'), ('limited_offer', 'Limited Offer'), ('collection', 'Collection Banner')], default='flash_sale', max_length=30),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
