# Generated by Django 6.0.3 on 2026-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('badminton', 'Badminton'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis'), ('hockey', 'Hockey'), ('sports cycle', 'Sports Cycle'), ('sports shone', 'Sports Shoe')], max_length=50),
        ),
    ]
