# Generated by Django 6.0.3 on 2026-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_banner_options_remove_banner_background_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='description',
            new_name='offer_text',
        ),
        migrations.AddField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='banner',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/backgrounds/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='collection_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/collections/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/products/'),
        ),
    ]
