# Generated by Django 6.0.3 on 2026-07-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='products.product'),
        ),
    ]
