# Generated by Django 6.0.3 on 2026-07-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_banner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#090d16', 'Dark Slate (Default)'), ('#1e3a8a', 'Royal Blue'), ('linear-gradient(135deg, #1e3a8a 0%, #0082c3 100%)', 'Blue-to-Cyan Gradient'), ('linear-gradient(135deg, #ef4444 0%, #991b1b 100%)', 'Red Gradient'), ('#ef4444', 'Solid Red'), ('#f3f4f6', 'Light Grey'), ('#faf9f6', 'Off-White')], default='#090d16', max_length=150),
        ),
    ]
