# Generated by Django 6.0.3 on 2026-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_banner_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('#1e3a8a', 'Blue'), ('#ef4444', 'Red'), ('#f3f4f6', 'Light Grey'), ('#faf9f6', 'Off-White')], default='#000000', max_length=150),
        ),
    ]
