# Generated by Django 6.0.3 on 2026-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_banner_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_color',
            field=models.CharField(blank=True, choices=[('#000000', 'Black'), ('#7393B3', 'Blue Grey'), ('#808080', 'Gray'), ('#f3f4f6', 'Light Grey'), ('#36454F', 'charcoal')], default='#000000', max_length=150),
        ),
    ]
