# Generated by Django 6.0.3 on 2026-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_banner_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(blank=True, choices=[('#ffffff', 'White'), ('#000000', 'Black'), ('#1e293b', 'Slate Dark'), ('#475569', 'Grey'), ('#1e3a8a', 'Blue')], default='#ffffff', max_length=50),
        ),
    ]
