# Generated by Django 6.0.3 on 2026-07-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_banner_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='text_color',
        ),
    ]
