# Generated by Django 6.0.3 on 2026-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_banner_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_demand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
